# Generated by Django 2.2.4 on 2019-08-31 12:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0005_auto_20190820_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='archived_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 14, 0, 8, 653864)),
        ),
    ]
