# Generated by Django 2.2.4 on 2019-08-20 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190816_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='archived_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 8, 54, 4, 892039)),
        ),
    ]
